"""
fake_generator.py
-----------------
Generates realistic fake values for detected PII entities.
Guarantees consistent, deterministic replacement across the entire document
and repeated runs.
"""

from faker import Faker
import hashlib
import re

# Cache for entity mappings during runtime
entity_map = {}


def _get_seeded_faker(original_text: str) -> Faker:
    """Creates a Faker instance seeded deterministically by the original text."""
    normalized = original_text.strip().lower()
    seed_int = int(hashlib.md5(normalized.encode('utf-8')).hexdigest(), 16) % (2**32)
    fake = Faker()
    Faker.seed(seed_int)
    return fake


def get_fake_value(entity_type: str, original: str) -> str:
    """
    Returns a realistic fake replacement for a detected PII entity.
    Consistent across identical entity occurrences.
    """
    key = original.strip()
    if not key:
        return original

    if key in entity_map:
        return entity_map[key]

    fake = _get_seeded_faker(key)

    if entity_type == "PERSON":
        value = fake.name()

    elif entity_type == "EMAIL_ADDRESS":
        # Extract username if available to match person fake if possible
        if "@" in key:
            local_part = key.split("@")[0]
            clean_name = local_part.replace(".", " ").replace("_", " ")
            person_fake = _get_seeded_faker(clean_name).name()
            username = person_fake.lower().replace(" ", ".")
            domain = fake.free_email_domain()
            value = f"{username}@{domain}"
        else:
            value = fake.email()

    elif entity_type == "PHONE_NUMBER":
        # Always generate a clean, uniform +91 phone number format
        digits = str(fake.random_number(digits=10, fix_len=True))
        value = f"+91 {digits[:5]} {digits[5:]}"

    elif entity_type == "LOCATION":
        # For single/two-word location names without digits (e.g. Maharashtra, India, Mumbai),
        # return a realistic city name rather than a full street address block.
        if len(key.split()) <= 2 and not any(char.isdigit() for char in key):
            value = fake.city()
        else:
            value = fake.address().replace("\n", ", ")

    elif entity_type == "ADDRESS":
        value = fake.address().replace("\n", ", ")

    elif entity_type in ("COMPANY", "ORGANIZATION"):
        base_fake = fake.company()
        # If base_fake generated by Faker already ends with a legal entity suffix (Ltd, LLC, Inc, PLC, Group, etc.),
        # do not append an additional ' Ltd'.
        if re.search(r"\b(?:Private\s+Limited|Pvt\.?\s*Ltd\.?|Limited|Ltd\.?|LLP|Inc\.?|Corporation|Corp\.?|Public\s+Limited\s+Company|PLC|LLC|Group)\b", base_fake, re.IGNORECASE):
            value = base_fake
        else:
            if re.search(r"\bLimited\b", key, re.IGNORECASE):
                value = f"{base_fake} Limited"
            elif re.search(r"\bLLP\b", key, re.IGNORECASE):
                value = f"{base_fake}, LLP"
            else:
                value = f"{base_fake} Ltd"

        # Clean up any trailing duplicate legal suffixes (e.g. "Ltd Ltd", "PLC Ltd", "LLC Ltd")
        value = re.sub(
            r"\b(Ltd|Limited|LLP|Inc|Corp|PLC|LLC|Group)\s+(Ltd|Limited|LLP|Inc|Corp|PLC|LLC)\b",
            r"\1",
            value,
            flags=re.IGNORECASE
        )

    elif entity_type in ("SSN", "US_SSN"):
        value = fake.ssn()

    elif entity_type == "CREDIT_CARD":
        value = fake.credit_card_number(card_type=None)

    elif entity_type in ("DATE_OF_BIRTH", "DOB"):
        value = fake.date_of_birth().strftime("%d/%m/%Y")

    elif entity_type == "IP_ADDRESS":
        value = fake.ipv4()

    elif entity_type == "AADHAAR":
        digits = str(fake.random_number(digits=12, fix_len=True))
        value = f"{digits[:4]} {digits[4:8]} {digits[8:]}"

    else:
        # Generic fallback using Faker sentence/word if needed
        value = f"[REDACTED_{entity_type}]"

    entity_map[key] = value
    return value